name: attendance_manager qa

run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - qa


jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4

          - name: Setup node
            uses: actions/setup-node@v4
            with:
                node-version: 22.x
                cache: npm

          - name: Install dependencies
            run: npm ci

          - name: Build / bundle
            run: npx expo export:embed --eager --platform ios --dev false
    
          - name: Run tests
            run: npm run test

    deploy:
        runs-on: macos-latest
        needs: build_and_test
        
        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4

          - name: Setup node
            uses: actions/setup-node@v4
            with:
                node-version: 22.x
                cache: npm

          - uses: expo/expo-github-action@v5
            with:
                expo-packager: npm
                expo-token: "${{ secrets.EXPO_TOKEN  }}"
                expo-cache: true

          - name: Build iOS App
            run: expo build --local -p ios --profile staging --non-interactive --output app.ipa

          - name: Deploy TestFlight
            uses: apple-actions/upload-testflight-build@v3
            with: 
                app-path: './app.ipa'
                issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
                api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
                api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}