name: attendance_manager dev

run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - dev


jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4

          - name: Install dependencies
            run: npm i

          - name: Compile typescript
            run: npx tsc --noEmit

          - name: Build / bundle
            run: npx expo export:embed --eager --platform ios --dev false

          - name: Run tests
            run: npm run test