name: build and test or deploy

run-name: ${{ github.event.head_commit.message }}
on:
    workflow_dispatch:
    push:
        branches:
            - development

env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    # TODO: continue here, conditional does not work
        # document that pipeline changes to workflow_dispatch only apply when on master branch
jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4

          - name: Install dependencies
            run: npm ci

          - name: Compile typescript
            run: npx tsc --noEmit

          - name: Build / bundle
            run: npx expo export:embed --eager --platform ios --dev false

          - name: Prebuild
            run: npx expo prebuild
    
          - name: Run tests
            run: npm run test

    # run only for qa and production
    deploy:
        runs-on: macos-15 # uses mandatory xcode v16
        needs: build_and_test
        if: ${{ github.head_ref || github.ref_name }} == 'qa' || ${{ github.head_ref || github.ref_name }} == 'production'
        steps:
          - name: Select Xcode 16.4 (for iOS 18)
            run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
            
          - name: Checkout repository 
            uses: actions/checkout@v4

          - name: Setup node
            uses: actions/setup-node@v4
            with:
                node-version: 22.x

          - name: Intall dependencies
            run: npm ci
            shell: bash

          - name: Setup eas
            uses: expo/expo-github-action@v8
            with:
                packager: npm
                token: "${{ secrets.EXPO_TOKEN }}"
                expo-version: latest
                eas-version: latest

          - name: Build iOS App
            run: eas build --local -p ios --profile ${{ env.BRANCH_NAME }} --non-interactive --output app.ipa

          - name: Deploy TestFlight
            uses: apple-actions/upload-testflight-build@v3
            with: 
                app-path: './app.ipa'
                issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
                api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
                api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}