name: attendance_manager qa

run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - qa


jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4

          - name: Install dependencies
            run: npm ci

          - name: Compile typescript
            run: npx tsc --noEmit

          - name: Build / bundle
            run: npx expo export:embed --eager --platform ios --dev false

          - name: Prebuild
            run: npx expo prebuild
    
          - name: Run tests
            run: npm run test

    deploy:
        # uses mandatory xcode v16
        runs-on: macos-15
        needs: build_and_test
        
        steps:
          - name: Checkout repository 
            uses: actions/checkout@v4

          - name: Setup node
            uses: actions/setup-node@v4
            with:
                node-version: 22.x

          - name: Intall dependencies
            run: npm ci
            shell: bash

          - name: Setup eas
            uses: expo/expo-github-action@v8
            with:
                packager: npm
                token: "${{ secrets.EXPO_TOKEN }}"
                expo-version: latest
                eas-version: latest

          - name: Write App Store Connect API key to file
            run: |
                echo "${{ secrets.APPSTORE_API_PRIVATE_KEY }}" > ./AuthKey.p8

          - name: Set up iOS credentials
            run: eas credentials --platform ios --non-interactive
            env:
                EXPO_IOS_DIST_P12_PASSWORD: ${{ secrets.APPSTORE_P12_PASSWORD }}
                # apparently required for the signing process, value does not matter
                EXPO_IOS_KEYCHAIN_PASSWORD: doNotChange 
                EAS_APPLE_APP_STORE_CONNECT_API_KEY_PATH: ./AuthKey.p8
                EAS_APPLE_APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
                EAS_APPLE_APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}

          - name: Build iOS App
            run: eas build --local -p ios --profile staging --non-interactive --output app.ipa

          - name: Deploy TestFlight
            uses: apple-actions/upload-testflight-build@v3
            with: 
                app-path: './app.ipa'
                issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
                api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
                api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}